version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 8088:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: deliverymanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

